image: pikalab/ci:ubuntu-jdk11-git-gradle-graphviz

before_script:
  - chmod +x mvnw
  - chmod +x bin/javalin-petstore.sh
  - source $HOME/.sdkman/bin/sdkman-init.sh

cache:
  paths:
    - samples/javalin/petstore/
    - $HOME/.gradle/
    - $HOME/.m2/
    - gradle/
    - .gradle/
    - build/

Compile:
  stage: build
  script:
    - ./mvnw clean package
    - bin/javalin-petstore.sh

Test:
  stage: test
  script:
    - cd samples/javalin/petstore
    - chmod +x gradlew
    - ./gradlew test
