image: pikalab/ci:ubuntu-jdk14-git-gradle-graphviz

before_script:
  - chmod +x mvnw
  - chmod +x bin/javalin.sh
  - source $HOME/.sdkman/bin/sdkman-init.sh

cache:
  paths:
    - samples/javalin/

Compile:
  stage: build
  script:
    - ./mvnw clean package
    - bin/javalin.sh

Test:
  stage: test
  script:
    - ls
    - cd samples/javalin
    - chmod +x gradlew
    - ./gradlew test
