/*
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: apiteam@swagger.io
 *
 * License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 */

package api;

import java.util.ArrayList;
import io.javalin.http.BadRequestResponse;
import java.util.concurrent.CompletableFuture;
import io.javalin.http.Context;
import java.util.HashMap;
import org.json.JSONArray;
import io.javalin.Javalin;
import io.javalin.plugin.json.JavalinJson;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import model.User;
import io.javalin.websocket.WsMessageContext;

import utils.Utilities;
import io.javalin.http.UnauthorizedResponse;

public abstract class UserAPI {

    private final String basePath;
    private int code = 200;

    public UserAPI(final String basePath) {
        this.basePath = Objects.requireNonNull(basePath);
    }

    protected final void setCode(final int code) {
        this.code = code;
    }

    public void registerRoutes(Javalin server) {
        server.post(this.basePath + "/user".replace("{",":").replace("}",""), this::createUser);
        server.post(this.basePath + "/user/createWithArray".replace("{",":").replace("}",""), this::createUsersWithArrayInput);
        server.post(this.basePath + "/user/createWithList".replace("{",":").replace("}",""), this::createUsersWithListInput);
        server.delete(this.basePath + "/user/{username}".replace("{",":").replace("}",""), this::deleteUser);
        server.get(this.basePath + "/user/{username}".replace("{",":").replace("}",""), this::getUserByName);
        server.get(this.basePath + "/user/login".replace("{",":").replace("}",""), this::loginUser);
        server.get(this.basePath + "/user/logout".replace("{",":").replace("}",""), this::logoutUser);
        server.put(this.basePath + "/user/{username}".replace("{",":").replace("}",""), this::updateUser);
        server.ws(this.basePath + "/User", ws -> {
            ws.onConnect(ctx -> System.out.println("Connected"));
            ws.onMessage(msgContext -> {
                String request = msgContext.message().split(">:")[0];
                switch (request){ 
                    case "POST/user": createUser(msgContext);
                        break;    
                    case "POST/user/createWithArray": createUsersWithArrayInput(msgContext);
                        break;    
                    case "POST/user/createWithList": createUsersWithListInput(msgContext);
                        break;    
                    case "DELETE/user/{username}": deleteUser(msgContext);
                        break;    
                    case "GET/user/{username}": getUserByName(msgContext);
                        break;    
                    case "GET/user/login": loginUser(msgContext);
                        break;    
                    case "GET/user/logout": logoutUser(msgContext);
                        break;    
                    case "PUT/user/{username}": updateUser(msgContext);
                        break;
                }
            });
            ws.onBinaryMessage(msgContext -> {
               byte[] data = msgContext.data();
               //TODO manage binary data
            });
            ws.onClose(ctx -> System.out.println("Connection Closed"));
            ws.onError(ctx -> System.out.println("Error occurred"));
        });
    }
    
    /**
    * Create user
    *
    * This can only be done by the logged in user.
    * 
    */
    public final void createUser(Context context) {
        
        // Check request content type
        String contentType = context.contentType();
        if (contentType == null || !contentType.contains("application/json"))
            throw new BadRequestResponse();

        
        
        
        
        
        // Body
        User body = context.bodyValidator(User.class).get();
        

        context.contentType("application/json; application/xml");
        
        this.createUserLogic(body);
        


        switch (this.code) {
            
            default: context.result("successful operation");
        }

        this.code = 200;
    }

    public abstract void createUserLogic(User body); // TODO The method should set the responding status code by calling setCode()

    /**
    * Creates list of users with given input array
    *
    * 
    * 
    */
    public final void createUsersWithArrayInput(Context context) {
        
        // Check request content type
        String contentType = context.contentType();
        if (contentType == null || !contentType.contains("application/json"))
            throw new BadRequestResponse();

        
        
        
        
        
        // Body
        JSONArray jsonArray = new JSONArray(context.body());
        List<User> body = new ArrayList<>();
        for (int i = 0; i < jsonArray.length(); i++) {
            User element =  JavalinJson.fromJson(jsonArray.getJSONObject(i).toString(), User.class);
            body.add(element);
        }

        context.contentType("application/json; application/xml");
        
        this.createUsersWithArrayInputLogic(body);
        


        switch (this.code) {
            
            default: context.result("successful operation");
        }

        this.code = 200;
    }

    public abstract void createUsersWithArrayInputLogic(List<User> body); // TODO The method should set the responding status code by calling setCode()

    /**
    * Creates list of users with given input array
    *
    * 
    * 
    */
    public final void createUsersWithListInput(Context context) {
        
        // Check request content type
        String contentType = context.contentType();
        if (contentType == null || !contentType.contains("application/json"))
            throw new BadRequestResponse();

        
        
        
        
        
        // Body
        JSONArray jsonArray = new JSONArray(context.body());
        List<User> body = new ArrayList<>();
        for (int i = 0; i < jsonArray.length(); i++) {
            User element =  JavalinJson.fromJson(jsonArray.getJSONObject(i).toString(), User.class);
            body.add(element);
        }

        context.contentType("application/json; application/xml");
        
        this.createUsersWithListInputLogic(body);
        


        switch (this.code) {
            
            default: context.result("successful operation");
        }

        this.code = 200;
    }

    public abstract void createUsersWithListInputLogic(List<User> body); // TODO The method should set the responding status code by calling setCode()

    /**
    * Delete user
    *
    * This can only be done by the logged in user.
    * 
    * PathParams:
    * username: The name that needs to be deleted
    * 
    */
    public final void deleteUser(Context context) {
        
        

        
        // Path params
        String username = context.pathParam("username", String.class).get();

        
        
        
        

        context.contentType("application/json; application/xml");
        
        this.deleteUserLogic(username);
        

        switch (this.code) {
            case 400:
                context.result("Invalid username supplied");
                context.status(400);
                break;
            case 404:
                context.result("User not found");
                context.status(404);
                break;
            default: 
        }

        this.code = 200;
    }

    public abstract void deleteUserLogic(String username); // TODO The method should set the responding status code by calling setCode()

    /**
    * Get user by user name
    *
    * 
    * 
    * PathParams:
    * username: The name that needs to be fetched. Use user1 for testing. 
    * 
    */
    public final void getUserByName(Context context) {
        
        

        
        // Path params
        String username = context.pathParam("username", String.class).get();

        
        
        
        

        context.contentType("application/json; application/xml");
        
        CompletableFuture<User> result = this.getUserByNameLogic(username);



        switch (this.code) {
            
            case 400:
                context.result("Invalid username supplied");
                context.status(400);
                break;
            case 404:
                context.result("User not found");
                context.status(404);
                break;
            default: context.result(result.thenApply(Utilities::serializeOne));
        }

        this.code = 200;
    }

    public abstract CompletableFuture<User> getUserByNameLogic(String username); // TODO The method should set the responding status code by calling setCode()

    /**
    * Logs user into the system
    *
    * 
    * 
    * 
    * QueryParams:
    * username: The user name for login
    * password: The password for login in clear text
    * 
    */
    public final void loginUser(Context context) {
        
        

        
        
        // Query params
        String username = context.queryParam("username", String.class).get();
        

        String password = context.queryParam("password", String.class).get();
        

        
        
        

        context.contentType("application/json; application/xml");
        
        CompletableFuture<String> result = this.loginUserLogic(username, password);



        switch (this.code) {
            
            case 400:
                context.result("Invalid username/password supplied");
                context.status(400);
                break;
            default: context.result(result.thenApply(Utilities::serializeOne));
        }

        this.code = 200;
    }

    public abstract CompletableFuture<String> loginUserLogic(String username, String password); // TODO The method should set the responding status code by calling setCode()

    /**
    * Logs out current logged in user session
    *
    * 
    * 
    */
    public final void logoutUser(Context context) {
        
        

        
        
        
        
        
        

        context.contentType("application/json; application/xml");
        
        this.logoutUserLogic();
        


        switch (this.code) {
            
            default: context.result("successful operation");
        }

        this.code = 200;
    }

    public abstract void logoutUserLogic(); // TODO The method should set the responding status code by calling setCode()

    /**
    * Updated user
    *
    * This can only be done by the logged in user.
    * 
    * PathParams:
    * username: name that need to be updated
    * 
    */
    public final void updateUser(Context context) {
        
        // Check request content type
        String contentType = context.contentType();
        if (contentType == null || !contentType.contains("application/json"))
            throw new BadRequestResponse();

        
        // Path params
        String username = context.pathParam("username", String.class).get();

        
        
        
        // Body
        User body = context.bodyValidator(User.class).get();
        

        context.contentType("application/json; application/xml");
        
        this.updateUserLogic(username, body);
        

        switch (this.code) {
            case 400:
                context.result("Invalid user supplied");
                context.status(400);
                break;
            case 404:
                context.result("User not found");
                context.status(404);
                break;
            default: 
        }

        this.code = 200;
    }

    public abstract void updateUserLogic(String username, User body); // TODO The method should set the responding status code by calling setCode()
    
    /**
    * Create user
    *
    * This can only be done by the logged in user.
    * 
    */
    public final void createUser(WsMessageContext context) {

        String message = context.message();
        String request = message.split(">:")[0];
        String requestMessage = message.split(">:", 2)[1];
        
        
        
        //Response
        context.send(this.createUserWsLogic(requestMessage));
    }

    public abstract String createUserWsLogic(String requestMessage);

    /**
    * Creates list of users with given input array
    *
    * 
    * 
    */
    public final void createUsersWithArrayInput(WsMessageContext context) {

        String message = context.message();
        String request = message.split(">:")[0];
        String requestMessage = message.split(">:", 2)[1];
        
        
        
        //Response
        context.send(this.createUsersWithArrayInputWsLogic(requestMessage));
    }

    public abstract String createUsersWithArrayInputWsLogic(String requestMessage);

    /**
    * Creates list of users with given input array
    *
    * 
    * 
    */
    public final void createUsersWithListInput(WsMessageContext context) {

        String message = context.message();
        String request = message.split(">:")[0];
        String requestMessage = message.split(">:", 2)[1];
        
        
        
        //Response
        context.send(this.createUsersWithListInputWsLogic(requestMessage));
    }

    public abstract String createUsersWithListInputWsLogic(String requestMessage);

    /**
    * Delete user
    *
    * This can only be done by the logged in user.
    * 
    * PathParams:
    * username: The name that needs to be deleted
    * 
    */
    public final void deleteUser(WsMessageContext context) {

        String message = context.message();
        String request = message.split(">:")[0];
        String requestMessage = message.split(">:", 2)[1];
        // Path params
        String username = context.pathParam("username", String.class).get();

        
        
        //Response
        context.send(this.deleteUserWsLogic(requestMessage, username));
    }

    public abstract String deleteUserWsLogic(String requestMessage, String username);

    /**
    * Get user by user name
    *
    * 
    * 
    * PathParams:
    * username: The name that needs to be fetched. Use user1 for testing. 
    * 
    */
    public final void getUserByName(WsMessageContext context) {

        String message = context.message();
        String request = message.split(">:")[0];
        String requestMessage = message.split(">:", 2)[1];
        // Path params
        String username = context.pathParam("username", String.class).get();

        
        
        //Response
        context.send(this.getUserByNameWsLogic(requestMessage, username));
    }

    public abstract String getUserByNameWsLogic(String requestMessage, String username);

    /**
    * Logs user into the system
    *
    * 
    * 
    * QueryParams:
    * username: The user name for login
    * 
    * password: The password for login in clear text
    * 
    */
    public final void loginUser(WsMessageContext context) {

        String message = context.message();
        String request = message.split(">:")[0];
        String requestMessage = message.split(">:", 2)[1];
        
        // Query params
        String username = context.queryParam("username", String.class, null).get();
        

        String password = context.queryParam("password", String.class, null).get();
        

        
        //Response
        context.send(this.loginUserWsLogic(requestMessage, username, password));
    }

    public abstract String loginUserWsLogic(String requestMessage, String username, String password);

    /**
    * Logs out current logged in user session
    *
    * 
    * 
    */
    public final void logoutUser(WsMessageContext context) {

        String message = context.message();
        String request = message.split(">:")[0];
        String requestMessage = message.split(">:", 2)[1];
        
        
        
        //Response
        context.send(this.logoutUserWsLogic(requestMessage));
    }

    public abstract String logoutUserWsLogic(String requestMessage);

    /**
    * Updated user
    *
    * This can only be done by the logged in user.
    * 
    * PathParams:
    * username: name that need to be updated
    * 
    */
    public final void updateUser(WsMessageContext context) {

        String message = context.message();
        String request = message.split(">:")[0];
        String requestMessage = message.split(">:", 2)[1];
        // Path params
        String username = context.pathParam("username", String.class).get();

        
        
        //Response
        context.send(this.updateUserWsLogic(requestMessage, username));
    }

    public abstract String updateUserWsLogic(String requestMessage, String username);
}
