/*
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.5
 * Contact: apiteam@swagger.io
 *
 * License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 */

import io.javalin.Javalin;
import api.PetAPI;
import api.StoreAPI;
import api.UserAPI;

public class Main {
    public static void main(String[] args) {
        String host = "localhost".split(":")[0];
        int port = 7000;
        if ("localhost".contains(":"))
            port = Integer.parseInt("localhost".split(":")[1]);
        Javalin server = Javalin.create().start(host, port);

        PetAPI petAPI = new PetAPI("/v2");
        petAPI.registerRoutes(server);

        StoreAPI storeAPI = new StoreAPI("/v2");
        storeAPI.registerRoutes(server);

        UserAPI userAPI = new UserAPI("/v2");
        userAPI.registerRoutes(server);

        
    }
}
